### PR TITLE
Enumerable

### PR DESCRIPTION
**Pull request by allun26**

### CODE REVIEW

**Comment by allun26** [comment]
i have fixed all linter errors except "C: Style/RedundantSelf: Redundant `self` detected". I think that the linter makes a mistake here, as "self" is needed. Otherwise, can you please explain what that mean?

**Comment by jofer86** [comment]
## Under Review!

**Review by jofer86 — APPROVED** [review]
# Amazing Work!!! :clap:  :clap: :tada: :tada:

Everything is working the way it should, the use of `yield` was spot on, only observation is to take care of the linter errors, which coincidently can be fixed quite easily. The redundant `self` is the first self you put on every method, I.E. `self.my_each { |i| result = yield(result, i) }` which in turn can be `my_each { |i| result = yield(result, i) }` and is still a valid statement, and cleaner :smile: .

## That's it, no need to ask for a new code review, just take care of the linter error, with the redundant self in the beginning of every method, and you can merge to master :tada: :tada:

**Comment by allun26** [comment]
thanks for the feedback :)

**Pull request merged**
